# 2.1. Data Maniputation.

### Basic Data Structure

In [11]:
import torch

# Create a tensor with evenly spaced values, starting at start(included) and ending at n(not included).
# By default, the interval length is 1.
x = torch.arange(0, 12, dtype=torch.float32)

# Use the numel method to calculate the total number of the tensor.
tot_num = x.numel()
print(tot_num)
# Access a tensor's shape by inspecting its shape attribute.
x_shape = x.shape

# Change the shape of the tensor by invoking reshape.
X = x.reshape(3,4)

# Put a "-1" for the shape component that should be inferred automatically.
X_auto = x.reshape(-1,2)

# Construct a tensor with all elements set to 0 and shape (shape0, shape1, shape2) by the zeros function.
X_0 = torch.zeros((2,3,4,5),dtype=torch.float32)

# Construct a tensor with all elements set to 1
X_1 = torch.ones((2,3,4))

# Create a tensor with random values obeying a standard Gaussian with mean = 0 and standard deviation = 1.
X_rand = torch.randn(3,4)

# Construct tensors by supplying the exact values for each element.
# Where the outermost list corresponds to axis 0 and the inner list corresponds to axis 1.
X_construct = torch.tensor([[2,1,3,5],[21,5,5,3],[2,5,3,6]])
X_construct



12


tensor([[ 2,  1,  3,  5],
        [21,  5,  5,  3],
        [ 2,  5,  3,  6]])

### Indexing and Slicing
- To access an element based on its position relative to the end of the list, we can use negative indexing. Finally, we can access whole ranges of indices via slicing (e.g., X[start:stop]), where the returned value includes the first index (start) but not the last (stop). 
- Finally, when only one index (or slice) is specified for a order tensor, it is applied along axis 0. Thus, in the following code, [-1] selects the last row and [1:3] selects the second and third rows.

In [19]:
import torch
X = torch.tensor([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

X[-1]
#X[1:3]

#X[1,2]=17
#X

#X[:2,:] = 12
#X

tensor([ 8,  9, 10, 11])

### Elementwise Operations
In mathematical notation, we denote such unary scalar operators (taking one input) by the signature : f:R->R.
. This just means that the function maps from any real number onto some other real number. Most standard operators, including unary ones like e^x , can be applied elementwise.

In [20]:
import torch
x = torch.arange(12,dtype=torch.float32)

torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

### Elementwise Binary Operators
Here, we produced the vector-valued F:R^d,R^d -> R^d by lifting the scalar function to an elementwise vector operation. The common standard arithmetic operators for addition (+), subtraction (-), multiplication (*), division (/), and exponentiation (**) have all been lifted to elementwise operations for identically-shaped tensors of arbitrary shape.

In [2]:
import torch
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

### Concatenate multiple tensors
- along aixs0 or axis1
- eg: (3,4) and (3,4) axis0:(3+3) axis1:(4+4)

In [22]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

### Logical Statement
- X == Y

In [3]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

### Sum
- .sum(): return a tensor with only one element

In [24]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X.sum()

tensor(66.)

### Broadcasting 
By now, you know how to perform elementwise binary operations on two tensors of the same shape. Under certain conditions, even when shapes differ, we can still perform elementwise binary operations by invoking the broadcasting mechanism. Broadcasting works according to the following two-step procedure: (i) expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape; (ii) perform an elementwise operation on the resulting arrays.

In [25]:
import torch
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Saving Memory
Since the location of the same variable after the calculation, we may use a method to perform the updates in place.
##### Using Y[:] = <"expression">
If the value of X is not reused in subsequent computations, we can also use X[:] = X + Y or X += Y to reduce the memory overhead of the operation.

In [29]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = torch.zeros_like(Y)
print('id(Y):',id(Y));
print('id(Z):',id(Z))
Y = X + Y
print('id(Y):',id(Y))
Z[:] = X + Y
print('id(Z):',id(Z))
before = id(X)
X += Y
id(X) == before

id(Y): 2213544970192
id(Z): 2213544973152
id(Y): 2213544968512
id(Z): 2213544973152


True

### Conversion to Other Python Objects
- Converting to a NumPy tensor (ndarray), or vice versa, is easy. The torch tensor and NumPy array will share their underlying memory, and changing one through an in-place operation will also change the other.
- To convert a size-1 tensor to a Python scalar, we can invoke the item function or Python’s built-in functions.

In [32]:
import numpy
import torch
X = torch.arange(1,4,0.5,dtype=torch.float32)
A = X.numpy()
B = torch.from_numpy(A)
type(A),type(B)

a = torch.tensor([4.5])
a,a.item(),float(a),int(a)

(tensor([4.5000]), 4.5, 4.5, 4)

# 2.2. Data Preprocessing

### Reading the dataset

In [ ]:
import os
import pandas as pd


# 2.3.Linear Algebra

### Scalars
Scalars are implemented as tensors that contain only one element. Below, we assign two scalars and perform the familiar addition, multiplication, division, and exponentiation operations.

In [ ]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

### Vectors
Vectors are implemented as 
-order tensors. In general, such tensors can have arbitrary lengths, subject to memory limitations. Caution: in Python, as in most programming languages, vector indices start at 
, also known as zero-based indexing, whereas in linear algebra subscripts begin at 
 (one-based indexing). 

In [2]:
import torch
x = torch.arange(3)
print(x[2])
print(len(x))
print(x.shape)

tensor(2)
3
torch.Size([3])


### Matrices

In [6]:
import torch
A = torch.arange(9).reshape(3,3)
print(A)
print(A.T)
print(A == A.T)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])


### Tensors

In [9]:
import torch
torch.arange(24).reshape(2,3,2,2)


tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]])

### Basic Properties of Tensor Arithmetic

In [ ]:
import torch
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

##### Hadamard product

In [10]:
import torch
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

##### Scalar multiplication

In [ ]:
import torch
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

##### Matrix-Matrix multiplication

### Reduction Sum

In [27]:
import torch
A = torch.arange(1,7,1,dtype=torch.float32).reshape(2,3)

print(A.shape,A.sum())

print(A.shape,A.sum(axis=0),A.sum(axis=0).shape)
print(A.shape,A.sum(axis=1),A.sum(axis=1).shape)

print(A.sum(axis=[0,1]) == A.sum())

print(A.mean(),A.sum() / A.numel())



torch.Size([2, 3]) tensor(21.)
torch.Size([2, 3]) tensor([5., 7., 9.]) torch.Size([3])
torch.Size([2, 3]) tensor([ 6., 15.]) torch.Size([2])
tensor(True)
tensor(3.5000) tensor(3.5000)


### Non-Reduction Sum

In [29]:
import torch
A = torch.arange(1,7,1,dtype=torch.float32).reshape(2,3)
sum_A = A.sum(axis=1, keepdims=True)
print(A)
print(sum_A, sum_A.shape)
print(A / sum_A)
print(A.cumsum(axis=0))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 6.],
        [15.]]) torch.Size([2, 1])
tensor([[0.1667, 0.3333, 0.5000],
        [0.2667, 0.3333, 0.4000]])
tensor([[1., 2., 3.],
        [5., 7., 9.]])


### Matrix-Vector Products

In [31]:
import torch
x = torch.arange(3,dtype=torch.float32)
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
print(A,x)
torch.mv(A, x),A@x

tensor([[0., 1., 2.],
        [3., 4., 5.]]) tensor([0., 1., 2.])


(tensor([ 5., 14.]), tensor([ 5., 14.]))

### Norms 

In [14]:
import torch
x = torch.tensor([3.0, 4.0, -1.0])
y = torch.ones((4,9))
print(torch.norm(x))  # Euclidean norm
print(torch.norm(y, p=2))  # L2 norm
print(torch.norm(y, p=1))  # L1 norm
print(torch.norm(y))  #  Frobenius norm

tensor(5.0990)
tensor(6.)
tensor(36.)
tensor(6.)


# Calculus

### Differentiation and Derivatives

In [33]:
%matplotlib inline
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l

def f(x):
    return 3 * x ** 2 - 4 * x

for h in 10.0**np.arange(-1,-6,-1):
    print(f'h={h:.5f},numerical limit={(f(1+h)-f(1))/h:.5f}')

h=0.10000,numerical limit=2.30000
h=0.01000,numerical limit=2.03000
h=0.00100,numerical limit=2.00300
h=0.00010,numerical limit=2.00030
h=0.00001,numerical limit=2.00003


### Visualization Utilities

We can visualize the slopes of functions using the matplotlib library. We need to define a few functions. As its name indicates, use_svg_display tells matplotlib to output graphics in SVG format for crisper images. The comment #@save is a special modifier that allows us to save any function, class, or other code block to the d2l package so that we can invoke it later without repeating the code, e.g., via d2l.use_svg_display().

In [ ]:
%matplotlib inline
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l

def use_svg_display():
    backend_inline.set_matplotlib_formats('svg')
    
